name: Lint and Format Check

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install Dependencies
        run: npm install --force

      - name: Run Linter
        run: npm run lint
        env:
          CI: true
